export interface BrdRes {
  data: {
    data: {
      access_key: string;
    };
  };
}

export interface BrudamResponse {
  message: string;
  status: number;
  data: Datum[];
}

export interface Datum {
  status: number;
  message: string;
  documento: string;
  dados: { [key: string]: null | string }[];
  prev_entrega: string;
  dias_entrega: string;
}

export interface SimexpressApiReturn {
  Retorno: string;
  Mensagem: string;
  consumidor: {
    pedidoCliente: string;
    destinatario: string;
    cidade: string;
    PrevisaoEntrega: string;
  };
  frete: {
    vlrPeso: string;
    vlrAdvalorem: string;
    vlrGRIS: string;
    vlrTotal: string;
    classificacao: string;
  };
  documentoOriginal: {
    'chave': string;
    'numero': string;
    'serie': string;
    'valor declarado': string;
  };
  tracking: [
    {
      tentativaEntrega: string;
      data: string;
      situacao: string;
      codigoInterno: string;
    }
  ];
}

// Generated by https://quicktype.io

export interface ConsultaJad {
  consulta: Consulta[];
}

export interface Consulta {
  df: Df;
  tracking: Tracking;
  previsaoEntrega: string;
  error?: ConsultaError;
}

export interface Df {
  nf: string;
  tpDocumento: number;
  cnpjRemetente: string;
}

export interface Tracking {
  codigo: string;
  shipmentId: string;
  dacte: string;
  dtEmissao: string;
  status: string;
  valor: number;
  peso: number;
  eventos: Evento[];
  volumes: Volume[];
  recebedor?: Recebedor;
}

export interface Recebedor {
  nome: string;
  doc: string;
  data: string;
}

export interface Evento {
  data: string;
  status: string;
  unidade: string;
}

export interface Volume {
  peso: number;
  altura: number;
  largura: number;
  comprimento: number;
}

export interface ConsultaError {
  id: number;
  descricao: string;
}
